# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
# obsidian_folder_path_str: 'Project Moon TTRPG' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'Project-Moon-TTRPG/Homepage.md'

# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: '/Project-Moon-TTRPG'

included_file_suffixes: ['jpg', 'jpeg', 'gif', 'png', 'bmp', 'pdf', 'mp4', 'webm', 'mp3', 'wav']

# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_glob:
  - ".obsidian"
  - ".venv"
  - "output"
  - "Images"

# Will be inputted into the Html template as page title
# Not used anywhere else atm.
site_name: 'Project Moon TTRPG'

toggles:
  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: True
  features:
    styling: 
      layout: documentation
    table_of_contents: 
      add_toc_when_missing: True
      only_show_for_multiple_headers: True
    graph:
      enabled: False
    folder_notes:
      enabled: True
      placement: 'inside folder'  
      naming: 'folder name'
    breadcrumbs:
      enabled: True